### ISSUE TITLE
安装hexo-generator-baidu-sitemap之后，hexo无法启动

### ISSUE THREAD

**Issue by jiankunking** [coneycode/hexo-generator-baidu-sitemap#31]
如果删除node_modules下的hexo-generator-baidu-sitemap 问题就好了
$ hexo s
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
TypeError: Cannot read property 'count' of undefined
    at Hexo.module.exports (I:\hexo\node_modules\hexo-baidu-url-submit\lib\generator.js:4:41)
    at Hexo.tryCatcher (I:\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (I:\hexo\node_modules\bluebird\js\release\method.js:15:34)
    at Promise.map.key (I:\hexo\node_modules\hexo\lib\hexo\index.js:318:20)
    at tryCatcher (I:\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (I:\hexo\node_modules\bluebird\js\release\map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (I:\hexo\node_modules\bluebird\js\release\promise_array.js:114:31)
    at MappingPromiseArray.init (I:\hexo\node_modules\bluebird\js\release\promise_array.js:78:10)
    at MappingPromiseArray._asyncInit (I:\hexo\node_modules\bluebird\js\release\map.js:30:10)
    at _drainQueueStep (I:\hexo\node_modules\bluebird\js\release\async.js:142:12)
    at _drainQueue (I:\hexo\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (I:\hexo\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (I:\hexo\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)

**Comment by coneycode** [comment]
从报错信息来看，导致出错的插件是hexo-baidu-url-submit，这个有单独安装过嘛？

**Comment by jiankunking** [comment]
> 从报错信息来看，导致出错的插件是hexo-baidu-url-submit，这个有单独安装过嘛？

没有

**Comment by coneycode** [comment]
从报错信息上看是hexo-baidu-url-submit的问题啊。。然后hexo-generator-baidu-sitemap并没有引用这个插件。。建议你看一看。

**Comment by jiankunking** [comment]
> 从报错信息上看是hexo-baidu-url-submit的问题啊。。然后hexo-generator-baidu-sitemap并没有引用这个插件。。建议你看一看。

收到 我看看吧 我也不清楚是哪个插件引用的
